name: Lint

runs:
  using: composite

  steps:
    - name: Check format with Black
      run: black --check .
      shell: bash
    - name: Check Typing with Mypy
      run: mypy src
      shell: bash
    - name: Lint with Flake8
      run: flake8 src
      shell: bash
    - name: Lint with Ruff
      run: ruff check src
      shell: bash
    - name: Check complexity
      run: complexipy .
      shell: bash
